ZPRP-10-dodac-endpoint-do-dodawania-warunkow-zaliczen
kozlowskimaciej/studentscheduler pull request #5
Opened 2024-04-09 18:47 UTC by kubao503

2024-04-09 19:19 UTC, kubao503 commented on studsched/app/api/base.py
> +    # Do some db staff
Not by me 😁

2024-04-09 19:40 UTC, kozlowskimaciej commented on studsched/app/api/base.py
> +    # Do some db staff
By your fingers

2024-04-09 19:41 UTC, kozlowskimaciej requested changes

2024-04-09 19:41 UTC, kozlowskimaciej commented on studsched/app/schemas/base.py
> +    COLL = auto()
There were more types than that , make the list complete

2024-04-09 19:41 UTC, kozlowskimaciej commented on studsched/app/schemas/base.py
> +    COLL = auto()
And don’t use abbreviations

2024-04-09 19:48 UTC, kubao503 commented on studsched/app/schemas/base.py
> +    COLL = auto()
Where were those types? What are you talking about?

2024-04-09 19:49 UTC, kubao503 commented on studsched/app/schemas/base.py
> +    COLL = auto()
I want to see them

2024-04-09 20:21 UTC, kozlowskimaciej commented on studsched/app/schemas/base.py
> +    COLL = auto()
Use your imagination

2024-04-14 16:09 UTC, kozlowskimaciej approved these changes

2024-04-14 16:13 UTC, merged